<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body>
<table border="2" cellpadding="10" cellspacing="0">
  <col width="45" />
  <col width="277" />
  <col width="92" />
  <col width="105" />
  <col width="40" />
  <col width="52" />
  <col width="20" />
  <col width="37" />
  <col width="59" />
  <col width="57" />
  <col width="65" />
  <col width="59" />
  <col width="65" />
  <col width="48" />
  <col width="67" />
  <tr height="52">
    <td colspan="15" height="52" width="100%"><table width="100%" border="0" cellspacing="0" cellpadding="2">
      <tr>
        <td><strong>DELIVERY CHALLAN</strong><br />
          GSTIN:<strong>09AAFFA1530L1ZL</strong><br />PAN NO:<strong>AAFFA1530L</strong></td>
        <td align="center"><strong>AERO CLUB</strong><br />
          C-15-16,Phase-II,NOIDA(U.P.),201305<br />Regional office:F-6,Sector-18,Noida(U.P.),201301</td>
        <td align="right" valign="top"><strong>Original for Recipient</strong></td>
      </tr>
    </table></td>
  </tr>
  <tr height="146">
    <td colspan="2" height="146" width="322">Attn To: <strong>dsfs</strong><br /><br />
      Name &amp; address of Recipient:<strong>AERO CLUB Unit-V KH NO C/2/2/2, Industrial Area,<br />
      Seladui(3505), Deharadun , Uttarkhand    - 248197</strong><br /><br />
      GSTIN:<strong>05AAFFA1530L1ZT</strong><br />
      Place Of Supply:<strong>UTTARAKHAND (05)</strong><br />
      Transportaion Details:<strong>By Road</strong></td>
    <td colspan="5" width="309">Ship To:<br />
      AERO CLUB<br />
      Unit-V KH NO C/2/2/2, Industrial Area, Seladui(3505), Deharadun , Uttarkhand    - 248197<br />
      GSTIN: 05AAFFA1530L1ZT</td>
    <td colspan="8" width="457">Challan No:2019-20/C16/0003 Date:01-11-2019<br />
      Purpose for sending goods:For Repairing on returnable<br />
      Jobwork Condition:<br />
      Nature of Processing:<br />
      Quantiity of goods to be Made:1 To be    returned within:180days</td>
  </tr>
  <tr height="24">
    <td colspan="2" height="24" width="322">Transporter Name:<strong>suraj</strong></td>
    <td colspan="5" width="309">Vehicle No:<strong>up19b 2012</strong></td>
    <td colspan="8" width="457"><strong>NOT FOR SALE</strong></td>
  </tr>
  <tr height="24">
    <td colspan="2" height="24" width="322">L/R/Builty No:</td>
    <td colspan="5" width="309">E-way Bill No:</td>
    <td colspan="2" width="96"></td>
    <td colspan="2" width="122"><strong>CGST</strong></td>
    <td colspan="2" width="124"><strong>SGST</strong></td>
    <td colspan="2" width="115"><strong>IGST</strong></td>
  </tr>
  <tr height="24">
    <td height="24" width="45"><strong>Sr&nbsp;No</strong></td>
    <td colspan="2" width="369"><strong>Description&nbsp;of&nbsp;goods</strong></td>
    <td width="105"><strong>HSN Code</strong></td>
    <td width="40"><strong>Qty</strong></td>
    <td width="52"><strong>Unit</strong></td>
    <td colspan="2" width="57"><strong>Rate</strong></td>
    <td width="59"><strong>Amount</strong></td>
    <td width="57"><strong>Rate</strong></td>
    <td width="65"><strong>Amount</strong></td>
    <td width="59"><strong>Rate</strong></td>
    <td width="65"><strong>Amount</strong></td>
    <td width="48"><strong>Rate</strong></td>
    <td width="67"><strong>Amount</strong></td>
  </tr>
  <tr height="27">
    <td height="27">1</td>
    <td colspan="2" width="369">MG 18626 ( )</td>
    <td>61163990</td>
    <td>1</td>
    <td width="52">LTR</td>
    <td colspan="2">447.50</td>
    <td>447.50</td>
    <td>0.00</td>
    <td>0.00</td>
    <td>0.00</td>
    <td>0.00</td>
    <td width="48"></td>
    <td>0.00</td>
  </tr>
  <tr height="18">
    <td colspan="2" height="18" width="322">NOT FOR SALE</td>
    <td width="92"></td>
    <td colspan="6" width="313">Total 1    447.50</td>
    <td width="57"></td>
    <td>0.00</td>
    <td width="59"></td>
    <td>0.00</td>
    <td colspan="2">0.00</td>
  </tr>
  <tr height="76">
    <td colspan="8" height="76" width="668">Total Amount In Words: Rupees Four Hundred Fourty-Seven Only<br />
      Weather Reverse Charge Applicable:No<br />
      Input tax Credit not available for this delivery challan</td>
    <td colspan="7" width="420">For AERO CLUB<br />
      Authorized Signatory</td>
  </tr>
  <tr height="24">
    <td colspan="2" height="24" width="322">Generated By:Pavan Yadav</td>
    <td width="92"></td>
    <td colspan="6" width="613">Certified that the particulars given are true &amp; correct</td>
    <td width="57"></td>
    <td width="65"></td>
    <td width="59"></td>
    <td width="65"></td>
    <td colspan="2" width="115">Request&nbsp;By:sdfsdf</td>
  </tr>
</table>
</body>
</html>
